#!/usr/bin/env python3
"""Static recompiler: 65816 code of Super Mario Kart -> C.

    recomp.py <rom.sfc> <tracedir> <outdir> [--symbols symbols.txt]

Uses the same analysis as disasm.py (traced + statically inferred instructions, M/X widths,
jump tables). Emits one C function per ROM bank. Every instruction becomes:

    L_80805C:                       // LDA.b $44
      CHK(0x805C);                  //   leave if an interrupt is pending / the frame loop must re-check
      FETCH(0x805C);                //   opcode fetch (same bus cycle as the hardware)
      cpu_op_a5(c);                 //   exact instruction semantics (emu/snes/cpu_core.inc)

Control flow is resolved statically: branches/jumps/calls inside the bank become `goto`,
returns and indirect jumps go through a per-bank `switch` dispatcher, anything else hands
control back to the interpreter. Because the per-opcode functions are the interpreter's own,
the recompiled build is cycle-identical to the interpreter, which `smkverify` checks frame by
frame. This is the faithful base layer; routines then get lifted into readable C one at a time
(see docs/ROADMAP.md, Phase 2).
"""
import argparse, os, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import disasm as D
from op65816 import OPS

BRANCH = {0x10, 0x30, 0x50, 0x70, 0x90, 0xB0, 0xD0, 0xF0}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("rom"); ap.add_argument("trace"); ap.add_argument("out")
    ap.add_argument("--symbols", default=None)
    a = ap.parse_args()
    rom = open(a.rom, "rb").read()
    R = D.ROMSZ
    cov = open(os.path.join(a.trace, "cov.bin"), "rb").read()
    ctx = open(os.path.join(a.trace, "covctx.bin"), "rb").read()
    edges = set()
    ep = os.path.join(a.trace, "edges.txt")
    if os.path.exists(ep):
        for line in open(ep):
            p = line.split()
            if len(p) == 3:
                edges.add((int(p[0], 16), int(p[1], 16), int(p[2], 16)))
    d = D.Disasm(rom, cov, ctx[:R], struct.unpack("<%dH" % R, ctx[R:3 * R]), ctx[3 * R:4 * R], ctx[4 * R:5 * R],
                 sorted(edges), D.load_symbols(a.symbols))
    d.place_executed()
    d.extend_static(d.find_jump_tables())
    d.collect_labels()
    d.owner_mid = set()
    for o, (ln, *_r) in d.ins.items():
        for i in range(1, ln):
            d.owner_mid.add(o + i)

    # C overrides: SMK_OVERRIDE(0xADDR, name) in recomp/overrides/*.c replaces the instruction at ADDR
    import glob, re
    overrides = {}
    ovdir = os.path.join(os.path.dirname(os.path.abspath(a.out)), "overrides")
    for fpath in sorted(glob.glob(os.path.join(ovdir, "*.c"))):
        if os.path.basename(fpath).startswith("_"):
            continue
        for m in re.finditer(r"SMK_OVERRIDE\(\s*0x([0-9A-Fa-f]{6})\s*,\s*(\w+)\s*\)", open(fpath).read()):
            t = D.rom_off(int(m.group(1), 16))
            if t is None or t not in d.ins:
                sys.exit("override %s: $%s is not a known instruction" % (m.group(2), m.group(1)))
            overrides[t] = m.group(2)
    # built-in gameplay rules: SMK_RULE(0xADDR, fn) in emu/rules.c (+ .inc); run only when they return true
    rulesmap = {}
    emu_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(a.out))), "emu")
    for fpath in sorted(glob.glob(os.path.join(emu_dir, "rules*.c")) + glob.glob(os.path.join(emu_dir, "rules*.inc"))):
        for m in re.finditer(r"SMK_RULE\(\s*0x([0-9A-Fa-f]{6})\s*,\s*(\w+)\s*\)", open(fpath).read()):
            t = D.rom_off(int(m.group(1), 16))
            if t is None or t not in d.ins:
                sys.exit("rule %s: $%s is not a known instruction" % (m.group(2), m.group(1)))
            rulesmap.setdefault(t, []).append(m.group(2))
    os.makedirs(a.out, exist_ok=True)
    nbanks = R >> 16
    total = 0
    for bank in range(nbanks):
        offs = sorted(o for o in d.ins if (o >> 16) == bank and o not in d.raw and (o & 0xFFFF) >= 0x8000)
        comp = set(offs)
        out = []
        w = out.append
        w("// GENERATED by tools/recomp.py from your ROM. Do not edit; do not distribute.\n")
        w("#include \"recomp_rt.h\"\n\n")
        for t, nms in sorted(rulesmap.items()):
            if (t >> 16) == bank:
                for nm in nms: w("bool %s(Cpu* c); // built-in rule (emu/rules.c)\n" % nm)
        for t, nm in sorted(overrides.items()):
            if (t >> 16) == bank:
                w("void %s(Cpu* c); // C override (recomp/overrides)\n" % nm)
        w("\nint smk_bank_%02X(Cpu* c) {\n" % (0x80 + bank))
        w("  const uint32_t y0 = recomp_y0;\n  const uint8_t k0 = c->k;\n  int ran = 0;\n")
        w("dispatch:\n  CHK(c->pc);\n  switch(c->pc) {\n")
        for o in offs:
            w("    case 0x%04X: goto L_%06X;\n" % (o & 0xFFFF, D.label_addr(o)))
        w("    default: return ran - 1;\n  }\n")
        for o in offs:
            ln, m8, x8, src = d.ins[o]
            op = rom[o]
            mn, mode = OPS[op]
            pc = o & 0xFFFF
            nxt = o + ln
            v = 0
            for i in range(ln - 1):
                v |= rom[o + 1 + i] << (8 * i)
            text = d.emit_ins(o) or mn
            if o in d.labels and (o in d.symbols or d.labels[o] != "data"):
                if o in d.symbols:
                    w("\n// ---- %s ----\n" % d.symbols[o])
            w("L_%06X: // %s%s\n" % (D.label_addr(o), text, "  [static]" if src == "static" else ""))
            w("  CHK(0x%04X);\n" % pc)
            for nm in rulesmap.get(o, []):
                w("  c->pc = 0x%04X; if(%s(c)) { ran = 1; if(c->k != k0) return 1; goto dispatch; }\n" % (pc, nm))
            if o in overrides:
                w("  ran = 1; c->pc = 0x%04X; %s(c);   // C override: must leave c->pc at the next instruction\n" % (pc, overrides[o]))
                w("  if(c->k != k0) return 1;\n  goto dispatch;\n")
                total += 1
                continue
            if mode == "imm":
                w("  GUARD(0x%04X, c->mf == %d);\n" % (pc, 1 if m8 else 0))
            elif mode == "imx":
                w("  GUARD(0x%04X, c->xf == %d);\n" % (pc, 1 if x8 else 0))
            w("  FETCH(0x%04X); cpu_op_%02x(c);\n" % (pc, op))

            def go(t):
                """jump to ROM offset t if compiled here, else leave via the dispatcher loop"""
                if t in comp:
                    return "goto L_%06X;" % D.label_addr(t)
                return "return 1;"
            bankbase = o & 0x70000
            if op in BRANCH:
                t = bankbase | ((nxt + (v - 256 if v & 0x80 else v)) & 0xFFFF)
                w("  if(c->pc == 0x%04X) %s\n" % (t & 0xFFFF, go(t)))
            elif op in (0x80, 0x82):          # BRA, BRL
                disp = (v - 256 if v & 0x80 else v) if op == 0x80 else (v - 65536 if v & 0x8000 else v)
                t = bankbase | ((nxt + disp) & 0xFFFF)
                w("  %s\n" % go(t)); total += 1; continue
            elif op in (0x4C, 0x20):         # JMP abs, JSR abs
                t = bankbase | v
                w("  %s\n" % (go(t) if v >= 0x8000 else "return 1;")); total += 1; continue
            elif op in (0x60, 0x6C, 0x7C, 0xFC):   # RTS, JMP (a), JMP (a,X), JSR (a,X): same bank
                w("  goto dispatch;\n"); total += 1; continue
            elif op in (0x5C, 0x22, 0x6B, 0x40, 0xDC, 0x00, 0x02):  # cross-bank / interrupts
                w("  return 1;\n"); total += 1; continue
            elif op in (0xCB, 0xDB):          # WAI, STP
                w("  return 0;\n"); total += 1; continue
            elif op in (0x54, 0x44):          # MVN/MVP repeat until A wraps
                w("  if(c->pc == 0x%04X) goto L_%06X;\n" % (pc, D.label_addr(o)))
            total += 1
            # fall through to the next instruction
            if nxt not in comp:
                w("  c->pc = 0x%04X; return 0;\n" % (nxt & 0xFFFF))
        w("}\n")
        with open(os.path.join(a.out, "bank_%02X.c" % (0x80 + bank)), "w") as f:
            f.write("".join(out))
    with open(os.path.join(a.out, "banks.h"), "w") as f:
        f.write("// GENERATED by tools/recomp.py\n#include \"cpu.h\"\n")
        for bank in range(nbanks):
            f.write("int smk_bank_%02X(Cpu* c);\n" % (0x80 + bank))
        f.write("static int (*const smk_banks[%d])(Cpu*) = {%s};\n" % (
            nbanks, ", ".join("smk_bank_%02X" % (0x80 + b) for b in range(nbanks))))
    print("recompiled %d instructions into %d bank functions -> %s" % (total, nbanks, a.out))


if __name__ == "__main__":
    main()
